<?php

######################################################################
# Widi - Who Is Doing It?
# ================================================
#
# Copyright (c) 2001 by
#                Gregorio Robles (grex@scouts-es.org)
#
# Widi: http://widi.berlios.de
#
# File with the main Spanish translation
# translated by Gregorio Robles (grex@scouts-es.org)
#
# This program is free software. You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 or later of the GPL.
######################################################################

switch($phrase) {

// Top strip Number 2
     case "Language": $tmp = "Idioma"; break;
     case "Go": $tmp = "Cambiar"; break;
     case "Selected Language": $tmp = "Idioma seleccionado"; break;

// Config inputs
     case "Form": $tmp = "Formulario"; break;
     case "Stats": $tmp = "Estad&iacute;sticas"; break;
     case "Comments": $tmp = "Comentarios"; break;
     case "Links": $tmp = "Enlaces"; break;

// Top title
     case "Knowing more about Open Source Developers":  $tmp = "Estudiando a los desarrolladores de C&oacute;digo Abierto (Open Source)"; break;

// Index - Form
     case "Introduction": $tmp = "Introducci&oacute;n"; break;

     case "what is this form about?": $tmp = "&iquest;Por qu&eacute; este formulario?"; break;
     case "tell a little about the project at the TU-Berlin": $tmp = "cuenta un poco sobre este proyecto en la TU de Berl&iacute;n"; break;
     case "Tell that all forms are anonymous and that they don't have to answer to anything.": $tmp = "Cuenta que todas las encuestas son an&oacute;nimas y que no hay que rellenar nada obligatoriamente"; break;
     case "Say who are the authors of this project": $tmp = "Cuenta qui&eacute;nes son los autores de todo esto"; break;
     case "Give thanx for filling it out": $tmp = "Dar las gracias por rellenarlo"; break;

     case "Personal Data": $tmp = "Datos Personales"; break;
     case "Name": $tmp = "Apellidos"; break;
     case "Surname": $tmp = "Nombre"; break;
     case "Alias": $tmp = "Sobrenombre"; break;
     case "Nationality": $tmp = "Nacionalidad"; break;
     case "Year of Birth": $tmp = "A&ntilde;o de Nacimiento"; break;
     case "Gender": $tmp = "Sexo"; break;
       case "Female": $tmp = "Mujer"; break;
       case "Male": $tmp = "Hombre"; break;

     case "Professional Data": $tmp = "Datos Profesionales"; break;

     case "Profession": $tmp = "Profesi&oacute;n"; break;
       case "Student": $tmp = "Estudiante"; break;
       case "Programmer": $tmp = "Programador"; break;
       case "Software Engineer": $tmp = "Ingeniero Software"; break;
       case "Other type of Engineering": $tmp = "Otro tipo de Ingeniero"; break;
       case "University professor/assistant": $tmp = "Profesor de Universidad"; break;
       case "Executive": $tmp = "Ejecutivo"; break;
       case "Consultant": $tmp = "Consultor"; break;
       case "Nothing to do with the software industry": $tmp = "Nada que tenga que ver con la industria del software"; break;

     case "Studies": $tmp = "Estudios"; break;
       case "Elementary School": $tmp = "Educaci&oacute;n General B&aacute;sica"; break;
       case "High School": $tmp = "Bachillerato"; break;
       case "(Lehre)": $tmp = "Formaci&oacute;n Profesional"; break;
       case "University Graduate": $tmp = "T&iacute;tulo Universitario"; break;
       case "Master": $tmp = "Maestr&iacute;a (M&aacute;ster)"; break;
       case "PhD": $tmp = "Doctorado"; break;

     case "What languages do you speak?": $tmp = "&iquest;Qu&eacute; idiomas hablas?"; break;
       case "English": $tmp = "Ingl&eacute;s"; break;
       case "German": $tmp = "Alem&aacute;n"; break;
       case "French": $tmp = "Franc&eacute;s"; break;
       case "Spanish": $tmp = "Espa&ntilde;ol"; break;
       case "Italian": $tmp = "Italiano"; break;
       case "Czech": $tmp = "Checo"; break;
       case "Portuguese": $tmp = "Portugu&eacute;s"; break;
       case "Japanese": $tmp = "Japon&eacute;s"; break;
       case "Other": $tmp = "Otros"; break;

     case "Email Domain": $tmp = "Dominio de tu correo-e"; break;

     case "Get you paid for doing Open Source?": $tmp = "&iquest;Te pagan por hacer programas Open Source?"; break;
       case "Blank": $tmp = "En Blanco"; break;
       case "Yes": $tmp = "S&iacute;"; break;
       case "No": $tmp = "No"; break;

     case "Computer experience": $tmp = "Experiencia con ordenadores"; break;

     case "Number of Open Source Projects you're involved in": $tmp = "N&uacute;mero de proyectos Open Source en los que est&aacute;s involucrado"; break;

     case "With which of these tools are you experienced?": $tmp = "&iquest;Con cu&aacute;les de estas herramientas tienes experiencia?"; break;

     case "Operating System / Distribution you use": $tmp = "Sistema Operativo / Distribuci&oacute;n que usas"; break;

     case "Desktops you use": $tmp = "Escritorio que utilizas"; break;
       case "Both": $tmp = "Ambos"; break;

     case "Favorite Editor": $tmp = "Editor Favorito"; break;

     case "Submit": $tmp = "Mandar"; break;

     case "Insert": $tmp = "Insertar"; break;


// Languages
	 case "English": $tmp = "Ingl&eacute;s"; break;
	 case "German": $tmp = "Alem&aacute;n"; break;
	 case "Spanish": $tmp = "Espa&ntilde;ol"; break;

// FAQ
     case "Frequently Asked Questions": $tmp = "Preguntas de Uso Frecuente"; break;
     case "Question": $tmp = "Pregunta"; break;
     case "Answer": $tmp = "Respuesta"; break;


// Comment
     case "Your Comment": $tmp = "Tu Comentario"; break;
     case "Subject": $tmp = "T&iacute;tulo"; break;
     case "Comment": $tmp = "Comentario"; break;
     case "Send": $tmp = "Mandar"; break;


// Announcements
    case "by": $tmp = "por"; break;
    case "on": $tmp = "el"; break;
    case "hits": $tmp = "hits"; break;


// Errors
     case "Access denied": $tmp = "Acceso denegado"; break;
     case "Error": $tmp = "Error"; break;
     case "and": $tmp = "y"; break;
     case "Database Access failed": $tmp = "Acceso a la base de datos fallido"; break;
     case "License description is not available": $tmp = "Descripci&oacute;n de licencia no disponible"; break;

// Footer

     case "Privacy Policy": $tmp = "Privacidad"; break;
     case "System Credits": $tmp = "Cr&eacute;ditos"; break;

// Insert

     case "Thank you": $tmp = "Gracias"; break;
     case "Give another time thanx for filling it out": $tmp = "Dar otra vez las gracias por haberlo rellenado"; break;   

// If no translation available, keep the original phrase
     default: $tmp = "$phrase"; break;
}
?>
