</td>
</tr>
</table>

<!-- footer -->

<table BORDER=0 CELLSPACING=0 CELLPADDING=2 WIDTH="100%" BGCOLOR="<?php echo $th_navstrip_bgcolor;?>">
<tr>
<td ALIGN=CENTER width=100%><span class="titlebar"><font color="<?php echo $th_navstrip_font_color;?>">Copyright
&copy;2001 <a href="<?php echo $org_url;?>" class="maintitlebar" TARGET="_blank"><?php echo $org_name;?></a>.</font></span></td>
</tr>
</table>
<!-- end footer -->

</body>
</html>