</td>
</tr>
</table>

<!-- footer -->

<table BORDER=0 CELLSPACING=0 CELLPADDING=2 WIDTH="100%" BGCOLOR="<?php echo $th_navstrip_bgcolor;?>">
<tr>
<td width=15%><span class="titlebar"><A HREF="<?php $sess->purl("privacy.php3"); ?>"><FONT COLOR="<?php echo $th_nav_bgcolor;?>"><?php echo $t->translate("Privacy Policy");?></font></<a>&nbsp;</span></td>
<td ALIGN=CENTER width=70%><span class="titlebar"><font color="<?php echo $th_navstrip_font_color;?>">Copyright
&copy;2001 <a href="<?php echo $org_url;?>" class="maintitlebar" TARGET="_blank"><?php echo $org_name;?></a>.</font></span></td>
<td width=15% align=right><span class="titlebar"><A HREF="http://widi.berlios.de/html" target="_blank"><FONT COLOR="<?php echo $th_nav_bgcolor;?>"><?php echo $t->translate("System Credits");?></font></<a>&nbsp;</span></td>
</tr>
</table>
<!-- end footer -->

</body>
</html>