<?php

######################################################################
# Widi - Who Is Doing It?
# ================================================
#
# Copyright (c) 2001 by
#                Gregorio Robles (grex@scouts-es.org)
#
# Widi: http://widi.berlios.de
#
# File with the main German translation
# translated by Gregorio Robles (grex@scouts-es.org)
# I hope somebody will do some corrections ;-)
#
# This program is free software. You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 or later of the GPL.
######################################################################

switch($phrase) {

// Top strip Number 2
     case "Language": $tmp = "Sprache"; break;
     case "Go": $tmp = "Los"; break;
     case "Selected Language": $tmp = "Gew&auml;hlte Sprache"; break;

// Config inputs
     case "Form": $tmp = "Formular"; break;
     case "Stats": $tmp = "Statistiken"; break;
     case "Comments": $tmp = "Kommentare"; break;
     case "Links": $tmp = $phrase; break;

// Top title
     case "Knowing more about Open Source Developers":  $tmp = "Eine Recherche &uuml;ber Open Source Entwicklern"; break;

// Index - Form
     case "Introduction": $tmp = "Einleitung"; break;

     case "what is this form about?": $tmp = "Warum dieses Formular?"; break;
     case "tell a little about the project at the TU-Berlin": $tmp = "Erz&auml;hl ein wenig &uuml;ber das Projekt an der TU-Berlin"; break;
     case "Tell that all forms are anonymous and that they don't have to answer to anything.": $tmp = "Erz&auml;hl, dass alle Eintr&auml;ge anonnym sind und dass man Felder frei lassen kann"; break;
     case "Say who are the authors of this project": $tmp = "Dass muss gesagt werden, wer die Authoren vom Projekt sind"; break;
     case "Give thanx for filling it out": $tmp = "Und nat&uuml;rlich danke geben f&uuml;r die Ausf&uuml;llung des Formulars"; break;

     case "Personal Data": $tmp = "Pers&ouml;nliche Daten"; break;
     case "Name": $tmp = $phrase; break;
     case "Surname": $tmp = "Vorname"; break;
     case "Alias": $tmp = "Spitzname"; break;
     case "Nationality": $tmp = "Staatsangeh&ouml;rigkeit"; break;
     case "Year of Birth": $tmp = "Geburtsjahr"; break;
     case "Gender": $tmp = "Geschlecht"; break;
       case "Male": $tmp = "M&auml;nnlich"; break;
       case "Female": $tmp = "Weiblich"; break;

     case "Professional Data": $tmp = "Berufliche Daten"; break;

     case "Profession": $tmp = "Beruf"; break;
       case "Student": $tmp = $phrase; break;
       case "Programmer": $tmp = "Programmierer"; break;
       case "Software Engineer": $tmp = "Softwareingenieur"; break;
       case "Other type of Engineering": $tmp = "Andere Ingenieurart"; break;
       case "University professor/assistant": $tmp = "Universit&auml;tsprofessor oder -assistent"; break;
       case "Executive": $tmp = "Executiver"; break;
       case "Consultant": $tmp = "Konsultor"; break;
       case "Nothing to do with the software industry": $tmp = "Nichts mit der Softwareindustrie zu tun"; break;

     case "Studies": $tmp = "Studium"; break;
       case "Elementary School": $tmp = "Hauptschulabschluss"; break;
       case "High School": $tmp = "Abitur"; break;
       case "(Lehre)": $tmp = "Lehre"; break;
       case "University Graduate": $tmp = "Universit&auml;tstitel"; break;
       case "Master": $tmp = "Master"; break;
       case "PhD": $tmp = "Doktortitel"; break;

     case "What languages do you speak?": $tmp = "Was f&uuml;r Sprachen k&ouml;nnen Sie sprechen?"; break;
       case "English": $tmp = "Englisch"; break;
       case "German": $tmp = "Deutsch"; break;
       case "French": $tmp = "Franz&ouml;sisch"; break;
       case "Spanish": $tmp = "Spanisch"; break;
       case "Italian": $tmp = "Italienisch"; break;
       case "Czech": $tmp = "Tschechisch"; break;
       case "Portuguese": $tmp = "Portuguesisch"; break;
       case "Japanese": $tmp = "Japanisch"; break;
       case "Other": $tmp = "Andere"; break;

     case "Email Domain": $tmp = "Email Dom&auml;n"; break;

     case "Get you paid for doing Open Source?": $tmp = "Werden Sie f&uuml;r ihr Open Source bezahlt?"; break;
       case "Blank": $tmp = "Leer"; break;
       case "Yes": $tmp = "Ja"; break;
       case "No": $tmp = "Nein"; break;

     case "Computer experience": $tmp = "Informatikkenntnisse"; break;

     case "Number of Open Source Projects you're involved in": $tmp = "Anzahl von Open Source Projekten in denen sie teilnehmen"; break;

     case "With which of these tools are you experienced?": $tmp = "Mit welchen der folgenden Tools sind sie verwandt?"; break;

     case "Operating System / Distribution you use": $tmp = "Welches Betriebssystem / Distribution verwenden Sie"; break;

     case "Desktops you use": $tmp = "Graphische Oberfl&auml;che"; break;
       case "Both": $tmp = "Beide"; break;

     case "Favorite Editor": $tmp = "Lieblingseditor"; break;

     case "Submit": $tmp = "Senden"; break;

     case "Insert": $tmp = "Einf&uuml;gen"; break;


// Languages
	 case "English": $tmp = "Englisch"; break;
	 case "German": $tmp = "Deutsch"; break;
	 case "Spanish": $tmp = "Spanisch"; break;

// FAQ
     case "Frequently Asked Questions": $tmp = "Oft gestellte Fragen"; break;
     case "Question": $tmp = "Frage"; break;
     case "Answer": $tmp = "Antwort"; break;


// Comment
     case "Your Comment": $tmp = "Ihr Kommentar"; break;
     case "Subject": $tmp = "Thema"; break;
     case "Comment": $tmp = "Kommentar"; break;
     case "Send": $tmp = "Senden"; break;


// Announcements
    case "by": $tmp = "von"; break;
    case "on": $tmp = "am"; break;
	case "hits": $tmp = "Zugriffe"; break;


// Errors
     case "Access denied": $tmp = "Zugriff verweigert"; break;
     case "Error": $tmp = "Fehler"; break;
     case "Parameter missing": $tmp = "Parameter fehlt"; break;
     case "and": $tmp = "und"; break;
     case "Database Access failed": $tmp = "Datenbankzugriff ist fehlgeschlagen"; break;
     case "Please try again": $tmp = "Bitte versuchen Sie es nochmal"; break;
     case "License description is not available": $tmp = "Lizenzbeschreibung ist nicht verfügbar"; break;

// Footer

     case "Privacy Policy": $tmp = "Privacy Policy"; break;
     case "System Credits": $tmp = "Systemkredite"; break;

// If no translation available, keep the original phrase
     default: $tmp = "$phrase"; break;
}
?>
